// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArbwimQ-dD-EoG2PyAYaSwnxBOxuROO98',
    appId: '1:906586242999:web:1b4bb72f718f784dbe7232',
    messagingSenderId: '906586242999',
    projectId: 'push-notifications-86257',
    authDomain: 'push-notifications-86257.firebaseapp.com',
    storageBucket: 'push-notifications-86257.firebasestorage.app',
    measurementId: 'G-5J8HXF7JBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-Q5KAgL2Sz6JlDs1ktOoXdtjZ3mgcDU',
    appId: '1:906586242999:android:9a0834b608001fc8be7232',
    messagingSenderId: '906586242999',
    projectId: 'push-notifications-86257',
    storageBucket: 'push-notifications-86257.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyN_u5CfIRd3Yg6u_h3A69DAEKdngTBnw',
    appId: '1:906586242999:ios:2b204f6ee425da33be7232',
    messagingSenderId: '906586242999',
    projectId: 'push-notifications-86257',
    storageBucket: 'push-notifications-86257.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyN_u5CfIRd3Yg6u_h3A69DAEKdngTBnw',
    appId: '1:906586242999:ios:2b204f6ee425da33be7232',
    messagingSenderId: '906586242999',
    projectId: 'push-notifications-86257',
    storageBucket: 'push-notifications-86257.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArbwimQ-dD-EoG2PyAYaSwnxBOxuROO98',
    appId: '1:906586242999:web:9b8026eb5bcd94b5be7232',
    messagingSenderId: '906586242999',
    projectId: 'push-notifications-86257',
    authDomain: 'push-notifications-86257.firebaseapp.com',
    storageBucket: 'push-notifications-86257.firebasestorage.app',
    measurementId: 'G-96PHJCG3G8',
  );
}
